extends Node

func _ready():
	var materials = [
		"res://assets/materials/wall_concrete_01.tres",
		"res://assets/materials/wall_concrete_02.tres",
		"res://assets/materials/floor_tile_01.tres",
		"res://assets/materials/floor_concrete_01.tres",
		"res://assets/materials/metal_structural_01.tres",
		"res://assets/materials/accent_team_blue.tres",
		"res://assets/materials/accent_team_red.tres",
	]
	
	var all_ok = true
	for mat_path in materials:
		var res = ResourceLoader.exists(mat_path)
		if res:
			var mat = load(mat_path)
			print("OK: " + mat_path + " -> " + str(mat.resource_name))
		else:
			print("FAIL: " + mat_path + " not found")
			all_ok = false
	
	if all_ok:
		print("\nAll materials loaded successfully.")
		get_tree().quit(0)
	else:
		print("\nSome materials failed to load.")
		get_tree().quit(1)
